// 选择车辆
export const PUSH_VEHICLE = 'PUSH_VEHICLE'
export const RECIVE_VEHICLES = 'RECIVE_VEHICLES'
// 选择服务
export const RECIVE_SERVICES = 'RECIVE_SERVICES'
export const CHOOSE_SERVICE = 'CHOOSE_SERVICE'
export const CANCEL_SERVICE_WINDOW = 'CANCEL_SERVICE_WINDOW'
export const RECIVE_ORDER_SERVICES = 'RECIVE_ORDER_SERVICES'
export const RECIVE_UNORDER_SERVICES = 'RECIVE_UNORDER_SERVICES'
export const RETURN_SELECTED_SERVICES = 'RETURN_SELECTED_SERVICES'
// 选择时间
export const RECIVE_SERVICE_TIME = 'RECIVE_SERVICE_TIME'
export const SHOW_SERVICE_TIME_WINDOW = 'SHOW_SERVICE_TIME_WINDOW'
export const CANCEL_SERVICE_TIME_WINDOW = 'CANCEL_SERVICE_TIME_WINDOW'
export const RECIVE_SELECTED_SERVICE_TIME = 'RECIVE_SELECTED_SERVICE_TIME'
